"""empty message

Revision ID: 0b091f903fb0
Revises: dda07272b244
Create Date: 2023-01-26 14:52:57.935093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b091f903fb0'
down_revision = 'dda07272b244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.drop_column('sede')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sede', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
