"""empty message

Revision ID: 23000f091593
Revises: 
Create Date: 2023-01-18 19:59:24.962352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23000f091593'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Provincia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nprovincia', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nsector', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tipo_Empleo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NEmpleo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('candidato', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Candidato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('primer_apellido', sa.String(length=120), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=120), nullable=False),
    sa.Column('puesto_trab', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('experiencia', sa.String(length=120), nullable=False),
    sa.Column('cv', sa.String(length=120), nullable=True),
    sa.Column('carta_presen', sa.String(length=120), nullable=True),
    sa.Column('tipo_emp', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('es_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['provincia'], ['Provincia.id'], ),
    sa.ForeignKeyConstraint(['tipo_emp'], ['Tipo_Empleo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(length=120), nullable=False),
    sa.Column('nombre_emp', sa.String(length=120), nullable=False),
    sa.Column('numero_trab', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=False),
    sa.Column('tipo_trab', sa.Integer(), nullable=False),
    sa.Column('sede', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('sector', sa.Integer(), nullable=False),
    sa.Column('indentificacion_fiscal', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector'], ['Sector.id'], ),
    sa.ForeignKeyConstraint(['tipo_trab'], ['Tipo_Empleo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Me_gusta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidato_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['Candidato.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['Empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Me_gusta')
    op.drop_table('Empresa')
    op.drop_table('Candidato')
    op.drop_table('user')
    op.drop_table('Usuario')
    op.drop_table('Tipo_Empleo')
    op.drop_table('Sector')
    op.drop_table('Provincia')
    # ### end Alembic commands ###
