"""empty message

Revision ID: 5eef0ca467e9
Revises: 5095ffb405a2
Create Date: 2023-01-16 21:41:59.538330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eef0ca467e9'
down_revision = '5095ffb405a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Candidato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('Candidato_usuario_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Usuario', ['usuario_id'], ['id'])
        batch_op.drop_column('usuario')

    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('Empresa_usuario_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Usuario', ['usuario_id'], ['id'])
        batch_op.drop_column('usuario')

    with op.batch_alter_table('Provincia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Nprovincia', sa.String(length=120), nullable=False))
        batch_op.drop_column('label')

    with op.batch_alter_table('Sector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Nsector', sa.String(length=120), nullable=False))
        batch_op.drop_column('label')

    with op.batch_alter_table('Tipo_Empleo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NEmpleo', sa.String(length=120), nullable=False))
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tipo_Empleo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('NEmpleo')

    with op.batch_alter_table('Sector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('Nsector')

    with op.batch_alter_table('Provincia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('Nprovincia')

    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Empresa_usuario_fkey', 'Usuario', ['usuario'], ['id'])
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('Candidato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Candidato_usuario_fkey', 'Usuario', ['usuario'], ['id'])
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
