"""empty message

Revision ID: b9f025fb17c3
Revises: 5c276f384b8f
Create Date: 2023-01-26 18:50:01.398665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f025fb17c3'
down_revision = '5c276f384b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sede', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.drop_column('sede')

    # ### end Alembic commands ###
