"""empty message

Revision ID: c330b5b63e52
Revises: 23000f091593
Create Date: 2023-01-22 09:25:12.621325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c330b5b63e52'
down_revision = '23000f091593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CandidatoEmp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IdTipoEmp', sa.Integer(), nullable=False),
    sa.Column('IdCandidato', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IdCandidato'], ['Candidato.id'], ),
    sa.ForeignKeyConstraint(['IdTipoEmp'], ['Tipo_Empleo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CandidatoEmp')
    # ### end Alembic commands ###
