"""empty message

Revision ID: d5e8aaf82d2c
Revises: b9f025fb17c3
Create Date: 2023-01-26 19:36:11.274542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e8aaf82d2c'
down_revision = 'b9f025fb17c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_trab', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Empresa', schema=None) as batch_op:
        batch_op.drop_column('numero_trab')

    # ### end Alembic commands ###
