"""empty message

Revision ID: dda07272b244
Revises: c330b5b63e52
Create Date: 2023-01-22 09:36:12.054466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda07272b244'
down_revision = 'c330b5b63e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PuestoTrabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NTrabajo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Candidato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puesto_trabajo', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'PuestoTrabajo', ['puesto_trabajo'], ['id'])
        batch_op.drop_column('puesto_trab')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Candidato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puesto_trab', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('puesto_trabajo')

    op.drop_table('PuestoTrabajo')
    # ### end Alembic commands ###
